import { useCallback, useState } from 'react';

import { useParams } from 'react-router';

import { useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';
import { v4 as uuidv4 } from 'uuid';

import {
  type Datasource,
  DatasourceKind,
  type DatasourceResultSet,
  type Notebook,
} from '@qwery/domain/entities';
import { getExtension } from '@qwery/extensions-sdk';
import { NotebookCellData, NotebookUI } from '@qwery/notebook';

import { useWorkspace } from '~/lib/context/workspace-context';
import { useNotebook } from '~/lib/mutations/use-notebook';
import { useGetDatasources } from '~/lib/queries/use-get-datasources';
import { useGetNotebookByProjectId } from '~/lib/queries/use-get-notebook';
import { useGetProjectBySlug } from '~/lib/queries/use-get-projects';

export default function NotebookPage() {
  const params = useParams();
  const slug = params.slug as string;
  const queryClient = useQueryClient();
  const { repositories } = useWorkspace();
  const projectRepository = repositories.project;
  const notebookRepository = repositories.notebook;
  const datasourceRepository = repositories.datasource;

  // Store query results by cell ID
  const [cellResults] = useState<Map<number, DatasourceResultSet>>(new Map());

  // Store query errors by cell ID
  const [cellErrors] = useState<Map<number, string>>(new Map());

  // Load project
  const project = useGetProjectBySlug(projectRepository, slug);

  // Load notebook for project
  const notebook = useGetNotebookByProjectId(
    notebookRepository,
    project.data?.id || '',
  );

  // Load datasources
  const savedDatasources = useGetDatasources(datasourceRepository);

  // Save notebook mutation
  const saveNotebookMutation = useNotebook(
    notebookRepository,
    () => {
      queryClient.invalidateQueries({
        queryKey: ['notebook', project.data?.id],
      });
    },
    (error) => {
      toast.error(
        `Failed to save notebook: ${error instanceof Error ? error.message : 'Unknown error'}`,
      );
    },
  );

  // Get plugin type from datasource provider
  const getDatasourceType = (datasource: Datasource): string => {
    if (!datasource.datasource_provider) {
      throw new Error(
        `Datasource ${datasource.id} is missing datasource_provider`,
      );
    }

    return datasource.datasource_provider;
  };

  const handleRunQuery = async (
    cellId: number,
    query: string,
    datasourceId: string,
  ) => {
    if (!query.trim()) {
      toast.error('Query cannot be empty');
      return;
    }

    const datasource = savedDatasources.data?.find(
      (ds) => ds.id === datasourceId,
    );
    if (!datasource) {
      toast.error('Datasource not found');
      return;
    }

    const datasourceType = getDatasourceType(datasource);

    if (datasource.datasource_kind === DatasourceKind.EMBEDDED) {
      const extension = await getExtension(datasourceType);
      if (!extension) {
        throw new Error('Extension not found');
      }
      const driver = await extension.getDriver(
        datasource.name,
        datasource.config,
      );
      if (!driver) {
        throw new Error('Driver not found');
      }
      const result = await driver.query(query);
      return result;
    }
    return null;
  };

  // Handle cells change - save notebook
  const handleCellsChange = useCallback(
    (cells: NotebookCellData[]) => {
      if (!project.data?.id) return;

      const now = new Date();
      const notebookId = notebook?.data?.id || uuidv4();
      const notebookData: Notebook = {
        id: notebookId,
        projectId: project.data?.id,
        name: notebook?.data?.name || 'Untitled Notebook',
        title: notebook?.data?.title || 'Untitled Notebook',
        description: notebook?.data?.description || '',
        slug: notebook?.data?.slug || '', // Will be auto-generated by repository
        version: notebook?.data?.version || 1,
        createdAt: notebook?.data?.createdAt || now,
        updatedAt: now,
        datasources:
          notebook?.data?.datasources ||
          savedDatasources.data?.map((ds) => ds.id) ||
          [],
        cells:
          notebook?.data?.cells ||
          cells.map((cell) => ({
            query: cell.query,
            cellType: cell.cellType,
            cellId: cell.cellId,
            datasources: cell.datasources,
            isActive: cell.isActive ?? true,
            runMode: cell.runMode ?? 'default',
          })),
      };

      saveNotebookMutation.mutate(notebookData);
    },
    [project, notebook, savedDatasources, saveNotebookMutation],
  );

  // Handle notebook change - save notebook
  const handleNotebookChange = useCallback(
    (changes: Partial<Notebook>) => {
      if (!project.data?.id || !notebook) return;

      const updatedNotebook: Notebook = {
        ...notebook?.data,
        ...changes,
        updatedAt: new Date(),
      } as Notebook;

      saveNotebookMutation.mutate(updatedNotebook);
    },
    [project, notebook, saveNotebookMutation],
  );

  // Map datasources to the format expected by NotebookUI
  const datasources = savedDatasources.data?.map((ds) => ({
    id: ds.id,
    name: ds.name,
  }));

  return (
    <NotebookUI
      notebook={notebook.data || undefined}
      datasources={datasources}
      onRunQuery={handleRunQuery}
      onCellsChange={handleCellsChange}
      onNotebookChange={handleNotebookChange}
      cellResults={cellResults}
      cellErrors={cellErrors}
    />
  );
}
