// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/version": {
    params: {};
  };
  "/healthcheck": {
    params: {};
  };
  "/organizations": {
    params: {};
  };
  "/org/:slug": {
    params: {
      "slug": string;
    };
  };
  "/prj/:slug": {
    params: {
      "slug": string;
    };
  };
  "/prj/:slug/notebook": {
    params: {
      "slug": string;
    };
  };
  "/prj/:slug/ds": {
    params: {
      "slug": string;
    };
  };
  "/prj/:slug/ds/new": {
    params: {
      "slug": string;
    };
  };
  "/prj/:slug/ds/:id/new": {
    params: {
      "slug": string;
      "id": string;
    };
  };
  "/ds/:slug": {
    params: {
      "slug": string;
    };
  };
  "/prj/:slug/playground": {
    params: {
      "slug": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/version" | "/healthcheck" | "/organizations" | "/org/:slug" | "/prj/:slug" | "/prj/:slug/notebook" | "/prj/:slug/ds" | "/prj/:slug/ds/new" | "/prj/:slug/ds/:id/new" | "/ds/:slug" | "/prj/:slug/playground";
  };
  "routes/version.ts": {
    id: "routes/version";
    page: "/version";
  };
  "routes/healthcheck.ts": {
    id: "routes/healthcheck";
    page: "/healthcheck";
  };
  "routes/layout/layout.tsx": {
    id: "routes/layout/layout";
    page: "/";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/organizations/layout.tsx": {
    id: "routes/organizations/layout";
    page: "/organizations";
  };
  "routes/organizations/index.tsx": {
    id: "routes/organizations/index";
    page: "/organizations";
  };
  "routes/organization/layout.tsx": {
    id: "routes/organization/layout";
    page: "/org/:slug";
  };
  "routes/organization/index.tsx": {
    id: "routes/organization/index";
    page: "/org/:slug";
  };
  "routes/project/layout.tsx": {
    id: "routes/project/layout";
    page: "/prj/:slug" | "/prj/:slug/notebook" | "/prj/:slug/ds" | "/prj/:slug/ds/new" | "/prj/:slug/ds/:id/new" | "/ds/:slug" | "/prj/:slug/playground";
  };
  "routes/project/index.tsx": {
    id: "routes/project/index";
    page: "/prj/:slug";
  };
  "routes/project/notebook.tsx": {
    id: "routes/project/notebook";
    page: "/prj/:slug/notebook";
  };
  "routes/project/datasources/index.tsx": {
    id: "routes/project/datasources/index";
    page: "/prj/:slug/ds";
  };
  "routes/project/datasources/sources.tsx": {
    id: "routes/project/datasources/sources";
    page: "/prj/:slug/ds/new";
  };
  "routes/project/datasources/new.tsx": {
    id: "routes/project/datasources/new";
    page: "/prj/:slug/ds/:id/new";
  };
  "routes/project/datasources/view.tsx": {
    id: "routes/project/datasources/view";
    page: "/ds/:slug";
  };
  "routes/project/playground.tsx": {
    id: "routes/project/playground";
    page: "/prj/:slug/playground";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/version": typeof import("./app/routes/version.ts");
  "routes/healthcheck": typeof import("./app/routes/healthcheck.ts");
  "routes/layout/layout": typeof import("./app/routes/layout/layout.tsx");
  "routes/index": typeof import("./app/routes/index.tsx");
  "routes/organizations/layout": typeof import("./app/routes/organizations/layout.tsx");
  "routes/organizations/index": typeof import("./app/routes/organizations/index.tsx");
  "routes/organization/layout": typeof import("./app/routes/organization/layout.tsx");
  "routes/organization/index": typeof import("./app/routes/organization/index.tsx");
  "routes/project/layout": typeof import("./app/routes/project/layout.tsx");
  "routes/project/index": typeof import("./app/routes/project/index.tsx");
  "routes/project/notebook": typeof import("./app/routes/project/notebook.tsx");
  "routes/project/datasources/index": typeof import("./app/routes/project/datasources/index.tsx");
  "routes/project/datasources/sources": typeof import("./app/routes/project/datasources/sources.tsx");
  "routes/project/datasources/new": typeof import("./app/routes/project/datasources/new.tsx");
  "routes/project/datasources/view": typeof import("./app/routes/project/datasources/view.tsx");
  "routes/project/playground": typeof import("./app/routes/project/playground.tsx");
};